# Evitar fallos

A veces, no podemos evitar un accidente. Va a ocurrir de todos modos, y todo lo que puedes hacer es prepararte para el impacto.

Hasta ahora.

Veamos un ejemplo basado en la lecci√≥n de ayer.
##

üëâ En este ejemplo, si el archivo 'Stuff.mine' no existe, entonces el c√≥digo arrojar√° un error 'no such file'.

```python
myStuff = []

f.open("Stuff.mine","r")
myStuff = eval(f.read())
f.close()

for row in myStuff:
  print(row)
```
## Prueba...excepto
La nueva construcci√≥n para evitar esto se llama `try.... except`.

Todo el c√≥digo que *deber√≠a* funcionar va dentro de `try`.
![alt text](image.png)

Los mensajes de error/instrucciones para manejar cualquier error al ejecutar el c√≥digo `try` van dentro de `except`.

![alt text](image-1.png)

üëâ As√≠:

```python
myStuff = []

try:
  f.open("Stuff.mine","r")
  myStuff = eval(f.read())
  f.close()
# Try to find a file called 'Stuff.mine' and open it

except:
  print("ERROR: Unable to load")
# If the file can't be found, show the error instead of crashing the whole program


for row in myStuff:
  print(row)
```

## ¬°Eres un Desarrollador de Software!

`try.... except` es genial para mejorar la experiencia del usuario y reducir la frustraci√≥n.

Sin embargo, hay problemas con s√≥lo poner el **c√≥digo completo** en un `` try except``.

Como desarrolladores (s√≠, ahora eres un desarrollador de software), ser√≠a bueno saber qu√© tipo de error se ha producido para que tengamos una mejor idea de c√≥mo solucionarlo.



Podemos decirle a `except` qu√© tipo de error(es) debe buscar.  `Exception` (E may√∫scula) significa `todo tipo`. He capturado el tipo de error en la variable `error` y lo he impreso para que me diga cu√°l es el error.
[Aqu√≠ hay una lista](https://www.w3schools.com/python/python_ref_exceptions.asp) de algunos c√≥digos de error `except` incorporados.
![alt text](image-2.png)


üëâ Mira como he extendido el `except` ahora.
```python
myStuff = []

try:
  f.open("Stuff.mine","r")
  myStuff = eval(f.read())
  f.close()
# Try to find a file called 'Stuff.mine' and open it

except Exception as err:
  print("ERROR: Unable to load")
  print(err)


for row in myStuff:
  print(row)
```

## Traceback

Incluso podr√≠amos deshacernos de la variable 'err' por completo e imprimir un traceback, que te mostrar√° el trazado de error rojo que ves cuando python se bloquea.

He creado una variable 'debugMode' en la parte superior de mi c√≥digo y puse el traceback en un `if` dentro del `except`.  

üëâ Esto me permite mostrar/ocultar los tracebacks f√°cilmente poniendo `debugMode` en True/False:

```python
debugMode = True
myStuff = []

try:
  f.open("Stuff.mine","r")
  myStuff = eval(f.read())
  f.close()
# Try to find a file called 'Stuff.mine' and open it

except Exception:
  print("ERROR: Unable to load")

  if debugMode:
    print(traceback)

for row in myStuff:
  print(row)
```
![alt text](image-3.png)

### ¬°Pru√©balo y mira qu√© errores puedes detectar!

# Errores comunes

*Primero, borra cualquier otro c√≥digo de tu fichero `main.py`. Copia cada fragmento de c√≥digo en `main.py` haciendo clic en el icono de copia en la parte superior derecha de cada cuadro de c√≥digo. A continuaci√≥n, pulsa `run` y comprueba qu√© errores se producen. Corrige los errores y pulsa "run" de nuevo hasta que est√©s libre de errores. Haz clic en "Respuesta" para comparar tu c√≥digo con el correcto.

## Int√©ntalo, int√©ntalo, int√©ntalo de nuevo

üëâ ¬øCu√°l es el problema aqu√≠?

```python
myStuff = []

try:
  f.open("Stuff.mine","r")
  myStuff = eval(f.read())
  f.close()

for row in myStuff:
  print(row)
```

<detalles> <sumario> üëÄ Respuesta </sumario>

- No hay `except` para atrapar el error. ``try` no se termina sin un except.

```python
misCosas = []

try:
  f.open("Cosas.m√≠as", "r")
  misCosas = eval(f.read())
  f.close()

except:
  print(traceback)

for fila en misCosas:
  print(fila))
```

</detalles>


# üëâ Reto del D√≠a 52

No hay lugar como Roma... O N√°poles, Mil√°n, incluso Nueva York si es necesario.  

Pero no los dudosos comerciantes de pan redondo con ingredientes sospechosos de las 2 de la ma√±ana que yo no visito de camino a casa despu√©s de salir por la noche.

¬°As√≠ es, vas a abrir una pizzer√≠a! Intenta no mancharte el teclado de anchoas. Esa cosa nunca se limpia.

En cualquier caso, tu programa de hoy debe:

1. Pedir al usuario que introduzca la cantidad y el tama√±o de las pizzas.
2. Multiplicar las dos entradas para calcular el coste de las pizzas.
3. Gu√°rdelo en una lista 2D con el nombre del usuario.
4. Utilice `try.... except` por **dos** razones:

    1. Incluye auto-guardado y auto-carga. √ösalo con el auto-load.
    2. Al convertir la cantidad de pizzas a un entero. Evita que el usuario bloquee el programa tecleando 'tres' en lugar de '3'. O cualquier otra entrada no entera. Si lo hace, p√≠dale que lo intente de nuevo.


Ejemplo:

```
üåüDave's Pizzas Esquivasüåü

¬øCu√°ntas pizzas? > tres
Debe introducir un car√°cter num√©rico, int√©ntelo de nuevo. > 3

¬øDe qu√© tama√±o? > XXXXXX

Nombre, por favor > David

Gracias David, tus pizzas costar√°n XXXXX
```

<detalles> <sumario> üí° Consejos </sumario>

- Utiliza subrutinas para `agregar` y `ver`.
- Utiliza un bucle `while.... true` para el men√∫ principal
- Usar una lista 2d para almacenar los detalles de cada pizza.
- Usa la selecci√≥n para decidir qu√© subrutina ejecutar, luego escribe la lista 2d en el fichero.
- Para a√±adir, obtenga todas las entradas en variables y a√±√°dalas a una lista. A√±ade esta lista a una 2d que almacene todos los detalles de la pizza.
- Para ver, obtener cada √≠ndice de una fila de la lista 2d a la vez.





</detalles>

La solucion la encontramos en [main.py](./main.py)